// GENERATED by scripts/build-web.js — do not hand edit.
// Service worker: cache the app shell so the PWA opens instantly (and offline).
// Data freshness is the bridge's job (localStorage), not the SW's — API calls
// are POSTs and pass straight through.
// 16e0b818320c is stamped by scripts/build-web.js so each build activates cleanly.

var CACHE = 'mp-shell-16e0b818320c';
var SHELL = ['./', './index.html', './manifest.webmanifest', './icon-192.png', './icon-512.png', './apple-touch-icon.png'];

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) { return c.addAll(SHELL); }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k !== CACHE; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

// Shell requests: serve from cache first, refresh it in the background.
self.addEventListener('fetch', function (e) {
  if (e.request.method !== 'GET' || new URL(e.request.url).origin !== self.location.origin) return;
  e.respondWith(
    caches.match(e.request).then(function (hit) {
      // no-cache: revalidate with the server instead of trusting the HTTP
      // cache — GitHub Pages sets max-age=600, which would make every app
      // update take ten stale minutes to arrive.
      var refresh = fetch(e.request, { cache: 'no-cache' }).then(function (res) {
        if (res && res.ok) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(e.request, copy); });
        }
        return res;
      }).catch(function () { return hit; });
      return hit || refresh;
    })
  );
});
